Create connect credentials template file
posit-conf-2024/ds-workflows-python pull request #45
Opened 2024-08-07 22:41 UTC by dotNomad

Over in the [Posit Publisher](https://github.com/posit-dev/publisher) we got environment variables working, but when we tested support in Posit Workbench we noticed that the `.bashrc` exports were getting detecting by the Posit Publisher extension process.

To enable persistent credential support in Workbench for Posit Conf 2024 we shifted to supporting a `~/.connect-credentials` file where a single URL and API Key can be specified similar to `CONNECT_SERVER` and `CONNECT_API_KEY`.

This PR introduces a template `.connect-credentials` file for easier onboarding for the workshop.

More about the issue can be read about here: https://github.com/posit-dev/publisher/issues/2088

2024-08-08 20:52 UTC, SamEdwardes commented
Thanks!

Can you also update the `init.sh` script to copy this to the correct place?

2024-08-08 20:54 UTC, SamEdwardes requested changes
Thanks!

Can you please also update the init.sh script to put this file in the correct place?

2024-08-08 20:59 UTC, dotNomad commented
> Can you please also update the init.sh script to put this file in the correct place?

Absolutely, added in https://github.com/posit-conf-2024/ds-workflows-python/pull/45/commits/1f9b4e7ed68828182b1fa62b557b0b7a1e0b5345

2024-08-09 14:25 UTC, SamEdwardes approved these changes
Awesome thank you!

2024-08-09 14:25 UTC, merged